-- Auto-generated by scripts/gen_dbeaver_sql.py -- do not hand-edit paths, rerun the generator instead.

INSTALL iceberg;
LOAD iceberg;

CREATE OR REPLACE VIEW patient_information AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_information/metadata/00001-36db57be-a9de-40be-acd5-8ca9aaee426b.metadata.json');
CREATE OR REPLACE VIEW patient_history AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_history/metadata/00002-bbe094dd-2abf-42a0-a316-d4def780d179.metadata.json');
CREATE OR REPLACE VIEW patient_visit AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_visit/metadata/00001-946fee2e-6a91-4777-a36f-a36addb1fbb2.metadata.json');
CREATE OR REPLACE VIEW patient_coding AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_coding/metadata/00005-81a15e88-19cc-4b1d-99c9-13afca31b8b0.metadata.json');
CREATE OR REPLACE VIEW patient_post_op_complications AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_post_op_complications/metadata/00001-3a198551-fe1a-492d-9865-70dfaec6cd43.metadata.json');
CREATE OR REPLACE VIEW patient_lda AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_lda/metadata/00001-16604843-4ce9-40d5-870b-1dad82150ed9.metadata.json');
CREATE OR REPLACE VIEW patient_procedure_events AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_procedure_events/metadata/00002-7b89c80a-2267-4203-b8a9-c2d0e1207fa3.metadata.json');
CREATE OR REPLACE VIEW patient_labs AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_labs/metadata/00059-2718b394-b1c0-453b-a547-3aee13d6fdd0.metadata.json');
CREATE OR REPLACE VIEW patient_medications AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/patient_medications/metadata/00056-04f406aa-fb77-4ac9-b7f6-c23f074180d5.metadata.json');
CREATE OR REPLACE VIEW flowsheets AS SELECT * FROM iceberg_scan('D:/Data_Science_Projects/Mover/iceberg_warehouse/bronze/flowsheets/metadata/00730-34046def-7b18-425f-91df-a332ccc2a81d.metadata.json');

-- sanity check (kept on one line so DBeaver's Ctrl+Enter can't split it mid-statement)
SELECT 'patient_information' AS tbl, COUNT(*) AS rows FROM patient_information UNION ALL SELECT 'flowsheets', COUNT(*) FROM flowsheets;
