"""Regenerates scripts/dbeaver_setup.sql from the live PyIceberg catalog, pinning each
view to the table's current metadata.json (no version-guessing needed). Run this again
whenever bronze tables get re-ingested/appended and the DBeaver views go stale."""
import sys
sys.path.insert(0, "/work/scripts")
from catalog import get_catalog

TABLES = [
    "patient_information", "patient_history", "patient_visit", "patient_coding",
    "patient_post_op_complications", "patient_lda", "patient_procedure_events",
    "patient_labs", "patient_medications", "flowsheets",
]

catalog = get_catalog()
lines = [
    "-- Auto-generated by scripts/gen_dbeaver_sql.py -- do not hand-edit paths, rerun the generator instead.",
    "",
    "INSTALL iceberg;",
    "LOAD iceberg;",
    "",
]
for t in TABLES:
    table = catalog.load_table(f"bronze.{t}")
    # metadata_location is "file:///D:/Data_Science_Projects/Mover/...". Strip the
    # "file://" scheme AND the one leading "/" before the drive letter -- DuckDB on
    # Windows needs "D:/..." with no leading slash for a direct file open (the
    # leading-slash-stripping only happens automatically for *internal* manifest
    # references, not the entry-point path you pass to iceberg_scan() yourself).
    loc = table.metadata_location.replace("file:///", "", 1)
    lines.append(f"CREATE OR REPLACE VIEW {t} AS SELECT * FROM iceberg_scan('{loc}');")

lines += [
    "",
    "-- sanity check (kept on one line so DBeaver's Ctrl+Enter can't split it mid-statement)",
    "SELECT 'patient_information' AS tbl, COUNT(*) AS rows FROM patient_information UNION ALL SELECT 'flowsheets', COUNT(*) FROM flowsheets;",
]

with open("/work/scripts/dbeaver_setup.sql", "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote scripts/dbeaver_setup.sql")
